-- Buraya SELECT scriptini yaz

--SELECT TOP 100 * FROM [CallCenter].[CUSTOMER_CONTACT_HISTORY] WITH (NOLOCK);

SELECT TOP 100 * FROM [COR].[LOG_ENTRY_PRODUCTION] WITH (NOLOCK);


--SELECT TOP 100 CONVERT(uniqueidentifier, CONVERT(binary(16), HASHBYTES('MD5', CONCAT(CAST(ID AS varchar(50)), 'CUSTOMER_CONTACT_HISTORY')))) AS Id, COALESCE(CALL_DATE, RECORD_DATE, GETDATE()) AS InsertTime, NULL AS UpdatedTime, LEFT(COALESCE(CAST(CALLCENTER_USER AS varchar(50)), CAST(AGENT AS varchar(50)), ''), 50) AS InsertUserId, LEFT(COALESCE(CAST(AGENT AS varchar(50)), CAST(CALLCENTER_USER AS varchar(50)), ''), 50) AS UpdateUserId, LEFT(COALESCE(CAST(CUSTOMER_NUMBER AS varchar(50)), '0'), 50) AS CustomerNumber, LEFT(COALESCE(CAST(CUSTOMER_NUMBER AS varchar(50)), '0'), 50) AS RelatedCustomerNumber, LEFT(COALESCE(CAST(CALL_ID AS varchar(100)), ''), 100) AS CallId, LEFT(COALESCE(CAST(CALLING_PHONE AS varchar(50)), ''), 50) AS CallingPhone, '' AS CalledPhone, LEFT(COALESCE(CAST(IVR_MENU_CODE AS varchar(100)), ''), 100) AS RedirectMenu, '' AS CampaignId, CAST(1 AS bit) AS IsCallClosed, CAST(0 AS bit) AS IsCallHeld, LEFT(COALESCE(CAST(NOTE AS varchar(500)), ''), 500) AS Note, LEFT(COALESCE(CAST(MOOD AS varchar(100)), ''), 100) AS Mood, CASE WHEN UPPER(LTRIM(RTRIM(COALESCE(CAST(ISBRANCH AS varchar(20)), '0')))) IN ('1', 'TRUE', 'Y') THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END AS IsBranch, LEFT(COALESCE(CAST(CHANNEL AS varchar(50)), 'CALLCENTER'), 50) AS Channel, LEFT(COALESCE(CAST(AGENT AS varchar(50)), ''), 50) AS AgentId, CAST(1 AS bit) AS IsActive, LEFT(COALESCE(CAST(IVR_MENU_CODE AS varchar(100)), ''), 100) AS ExternalRedirectMenu, LEFT(COALESCE(CAST(CALLCENTER_USER AS varchar(50)), ''), 50) AS AgentUserId 
--FROM [CallCenter].[CUSTOMER_CONTACT_HISTORY] WITH (NOLOCK);



